# Generated by Django 3.1.7 on 2021-06-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'ordering': ['-created'], 'verbose_name': 'transacción', 'verbose_name_plural': 'transacciones'},
        ),
    ]
