# Generated by Django 3.1.7 on 2021-06-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_auto_20210626_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=10, verbose_name='tipo'),
        ),
    ]
