# Generated by Django 3.1.7 on 2021-07-01 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_auto_20210630_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Trabajo', 'Trabajo'), ('Regalo', 'Regalo'), ('Comida', 'Comida'), ('Ropa', 'Ropa'), ('Gustico', 'Gustico')], max_length=20, verbose_name='Categoría')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.category', verbose_name='Categoría'),
        ),
    ]
