# Generated by Django 3.1.7 on 2021-07-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_auto_20210701_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], default='Ingreso', max_length=10, null=True, verbose_name='Tipo'),
        ),
    ]
