# Generated by Django 3.1.7 on 2021-07-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_auto_20210705_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=10, verbose_name='Tipo'),
        ),
    ]
