# Generated by Django 3.1.7 on 2021-07-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0009_auto_20210705_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], default=None, max_length=10, verbose_name='Tipo'),
        ),
    ]
