# Generated by Django 3.1.7 on 2021-07-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0010_auto_20210705_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(max_length=10, verbose_name='Tipo'),
        ),
    ]
