# Generated by Django 3.1.7 on 2021-07-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0012_auto_20210709_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='categoria',
            field=models.ManyToManyField(related_name='categoria', to='cuentas.Category', verbose_name='Categoría'),
        ),
    ]
