# Generated by Django 3.1.7 on 2021-07-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0013_auto_20210712_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='saldo',
            field=models.FloatField(default=1, verbose_name='Saldo'),
            preserve_default=False,
        ),
    ]
