# Generated by Django 3.1.7 on 2021-07-17 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0015_auto_20210717_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.FloatField(blank=True, null=True, verbose_name='Saldo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'saldo',
                'verbose_name_plural': 'saldos',
            },
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuentas.saldototal', verbose_name='Saldo'),
            preserve_default=False,
        ),
    ]
